# Setup
title:        Hello world
tagline:      newpolaris's WebGL test page
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       newpolaris
  url:        https://newpolaris.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
